project:
  type: website
  output-dir: docs

website:
  title: "Test_Website_Feburary_2025"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: floating
    search: true
    contents: 
     - text: "About"
       href: about.qmd
     - href: Uploading_sediment_16s_rRNA_data_to_SRA.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
